### ISSUE TITLE
Copying of the provided containers in `boolinq::from`

### ISSUE THREAD

**Issue by elricbk** [k06a/boolinq#14]
If I correctly read the code – all the versions of `boolinq::from` copy provided container to the `TC` field of the `IteratorContainerPair`. Is this design intentional? Because it could be rather expensive on large collections.

Also, won't simple code like this do:

    template <typename Container>
    LinqObject<... smth. with decltype(std::begin(containter) ...> from(
             const Container& container) {
        return from(std::begin(container), std::end(container));
    }

?

**Comment by k06a** [comment]
@elricbk thanks for this information. Recently I have no much time to support this lib. But I hope I will be able to merge some improvements :) Looks like @babelvit, who fixed this issue.
