### ISSUE TITLE
'groupBy' marked as today supported in readme is not implemented

### ISSUE THREAD

**Issue by jianghj** [k06a/boolinq#21]

**Comment by k06a** [comment]
Looks like it was implemented in boolinq 1.0 and not yet implemented in 2.0. :(

**Comment by deathwishdave** [comment]
This is kind of a deal breaker for me!

**Comment by deathwishdave** [comment]
k06a, is boolinq 1.0 still available?

**Comment by k06a** [comment]
@deathwishdave hi, yep, it is available in git history.

**Comment by k06a** [comment]
Will try to implement it soon

**Comment by deathwishdave** [comment]
@k06a thanks!

**Comment by k06a** [comment]
@deathwishdave try to deliver it tomorrow with new version `v3`.

**Comment by k06a** [comment]
@deathwishdave you can try `groupBy` from this version: https://github.com/k06a/boolinq/blob/7d8da6a02fa29daa284a0d8ca9f4a1e5b192c49c/include/boolinq/boolinq.h

It returns pairs of keys and groups: `std::pair<TKey, Linq>`

**Comment by deathwishdave** [comment]
@k06a Thanks very much for the quick turnaround! I will try it out today.

**Comment by k06a** [comment]
@deathwishdave just merged `v3` into `master`
