### ISSUE TITLE
Example appears to crash on MSVC 2017

### ISSUE THREAD

**Issue by sharpe5** [k06a/boolinq#34]
I've been using C# and LINQ for years, so this library looks just fantastic, as I am using C++ now and really miss how expressive C# is.

I run this example code:

```
int src[] = {1,2,3,4,5,6,7,8};
std::vector<int> dst = boolinq::from(src)
    .where([](int a) { return a % 2 == 1; }) // 1,3,5,7
    .select([](int a) { return a * 2; }) // 2,6,10,14
    .where([](int a) { return a > 2 && a < 12; }) // 6,10
    .toStdVector();
```

I get an exception in this function:
```
////////////////////////////////////////////////////////////////
// Linq Creators
////////////////////////////////////////////////////////////////

template<typename T>
Linq<std::pair<T, T>, typename std::iterator_traits<T>::value_type> from(const T & begin, const T & end)
{
    return Linq<std::pair<T, T>, typename std::iterator_traits<T>::value_type>(
        std::make_pair(begin, end),
        [](std::pair<T, T> &pair) {
            if (pair.first == pair.second) {
                throw LinqEndException();
            }
            return *(pair.first++);
        }
    );
}
```

The exception is on this line:
```
return *(pair.first++);
```

The exception is:
```
Exception thrown at 0x00007FFB4A13A388 in DemoRange.exe: Microsoft C++ exception: boolinq::LinqEndException at memory location 0x000000807813CCF4.
```

Environments tried in:
```
MSVC 2017 15.9.16 + MSVC with "ISO C++17 Standard (/std:c++17)"
MSVC 2017 15.9.16 + Intel Compiler v19.0 
```

**Comment by k06a** [comment]
The library works on exceptions, actually on a single exception. You should skip it, it should be handled in a proper way.

**Comment by k06a** [comment]
I mean Visual Studio for some reason decided to show you not a really unhandled exception but handled one.

**Comment by sharpe5** [comment]
Ah, that makes sense. I'll try skipping the exception.

I'm from a C# background, so that exception looked like a memory access
violation to me. The exception appears to occur on a pointer access. It's
probably an issue with the MSVC debugger.

**Comment by sharpe5** [comment]
Closing as not an issue. Thanks for the quick response, and thank you for the fantastic work on the library.

**Comment by k06a** [comment]
@sharpe5 you're welcome! Tell me which functions are missing and you wish to see, I'll try to deliver it.
