### ISSUE TITLE
Как IEnumerable

### ISSUE THREAD

**Issue by Boklazhenko** [k06a/boolinq#35]
Привет. Нет возможности проверить, но очень интересно.

В примерах увидел, что везде цепочка вызовов заканчивается toVector to...

А можно написать как то так

for(auto&& i : from({1,2,3})
                                  .where([] (auto&& i) {
                                               return i % 2 == 0;
                                   }))
    Что то делаем...

auto enumerable = from(...).where(...)
Не будет вычисляться до того момента пока не сделаем функцию to...? Или не начнём итертровать? Как в дот нет? Спасибо

**Comment by k06a** [comment]
Да, конечно, можно закончить каким-нибудь for_each и все будет обрабатываться ленивым (lazy) способом, вытягиваясь сквозь всю цепочку.

**Comment by k06a** [comment]
>auto enumerable = from(...).where(...)
>Не будет вычисляться до того момента пока не сделаем функцию to...? Или не начнём итертровать? Как в дот нет? Спасибо

Да, именно так.
