### ISSUE TITLE
SelectMany

### ISSUE THREAD

**Issue by rohanaceres** [k06a/boolinq#38]
Hi,

How can I `selectMany` with objects? For example:

```
auto concatInnerList =
    from(*myObj)
        .selectMany([](const MyObj& myObjTemp) { return myObjTemp.innerList; })
        .toStdArray();
```

`myObj` is a `std::vector<MyObject>` which contains an inner list object std::vector<InnerList>.

**Comment by k06a** [comment]
Hi @rohanaceres, try `return from(myObjTemp.innerList);`

**Comment by k06a** [comment]
You can find all examples in `test` folder: https://github.com/k06a/boolinq/blob/master/test/SelectManyTest.cpp#L29
