### ISSUE TITLE
Warnings during compilation

### ISSUE THREAD

**Issue by martinrotter** [k06a/boolinq#42]
boolinq.h:67: Warning: C4100: 'index': unreferenced formal parameter

Here is source code, pls fix. Also, there are some other unreferences local variables/parameters which also produce these warnings.

```cpp
        void for_each(std::function<void(T)> apply) const
        {
            return for_each_i([apply](T value, int index) { return apply(value); });
        }
```

**Comment by k06a** [comment]
Thx, will merge your PR

**Comment by martinrotter** [comment]
I did not commit any PR, but I see someone else did.

**Comment by k06a** [comment]
Oh, @martinrotter sorry. Just merged it anyway.
