### ISSUE TITLE
C++ 20 Windows Build Problem

### ISSUE THREAD

**Issue by TaeZStkyoht** [k06a/boolinq#49]
I am using your library. It could be built with C++ 17. But now I've changed my projects to be built with C++ 20 and it gives errors.  Simple example error is like that:
```
int main() {
	vector<int> asd = { 3, 4, 1, -1, 565 };
	for (int b : from(asd).where([](int a) { return a > 3; }).toStdVector())
		cout << b << endl;

	return 0;
}
```
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0135	class "boolinq::Linq<std::tuple<boolinq::Linq<std::pair<std::_Vector_const_iterator<std::_Vector_val<std::conditional_t<true, std::_Simple_types<int>, std::_Vec_iter_types<int, size_t, ptrdiff_t, int *, const int *, int &, const int &>>>>, std::_Vector_const_iterator<std::_Vector_val<std::conditional_t<true, std::_Simple_types<int>, std::_Vec_iter_types<int, size_t, ptrdiff_t, int *, const int *, int &, const int &>>>>>, int>, int>, int>" has no member "toStdVector"
```

**Comment by k06a** [comment]
@TaeZStkyoht seems really strange that `class "boolinq::Linq<***>" has no member "toStdVector"`, because it has this method:

https://github.com/k06a/boolinq/blob/a362fe917a47a784e818c6b27de29833776eefbc/include/boolinq/boolinq.h#L600-L607

**Comment by TaeZStkyoht** [comment]
I'm using Visual Studio 2019 v16.11.1 on Windows. By the way it's not only toStdVector but also almost all other functions.

**Comment by RoqueDeicide** [comment]
result_of is deprecated in c++ 20 and needs to be replaced with invoke_result.

**Comment by k06a** [comment]
@RoqueDeicide @TaeZStkyoht @ZumZoom any ideas how to write universal code using `result_of` in pre-C++17 and `invoke_result_t` in C++17+?

**Comment by Mrhyuan** [comment]
It seems the version on vcpkg and conan is still 3.0.2. Any plan to update? Thx.

**Comment by k06a** [comment]
@Mrhyuan requested cvpkg upgrade here: https://github.com/microsoft/vcpkg/issues/22173

**Comment by k06a** [comment]
@Mrhyuan done via https://github.com/microsoft/vcpkg/pull/22177

**Comment by Mrhyuan** [comment]
> @Mrhyuan done via [microsoft/vcpkg#22177](https://github.com/microsoft/vcpkg/pull/22177)

So fast thank you so much

**Comment by TaeZStkyoht** [comment]
@k06a Ok "toStdVector" works now but some of them still doesn't work (especially "select"). Did you try your examples on your readme page? They don't work. Now I'm using Visual Studio 2019 16.11.8, _MSC_VER 1929, _MSVC_LANG 202002L. Your defined macro (The result_of was deprecated since C++20, so redefine it using invoke_result) is active because these versions satisfy it.

Your example:
```
int src[] = { 1,2,3,4,5,6,7,8 };
	auto dst = from(src).where([](int a) { return a % 2 == 1; })      // 1,3,5,7
		.select([](int a) { return a * 2; })           // 2,6,10,14
		.where([](int a) { return a > 2 && a < 12; }) // 6,10
		.toStdVector();
```

Errors:
- 'boolinq::Linq<std::tuple<boolinq::Linq<std::tuple<boolinq::Linq<std::pair<const int *,const int *>,int>,int>,T>,int>,_TRet> boolinq::Linq<std::tuple<boolinq::Linq<std::pair<const int *,const int *>,T>,int>,T>::select(F) const': could not deduce template argument for '_TRet'
- 'boolinq::Linq<std::tuple<boolinq::Linq<std::pair<const int *,const int *>,int>,int>,T>::select': no matching overloaded function found

![image](https://user-images.githubusercontent.com/3801692/147809883-4fb9a96e-7dce-466c-894f-59406b8ccb0c.png)

It still works with C++17 on Windows and any modern C++ version on Linux.

@RoqueDeicide Did you also try your work?

**Comment by k06a** [comment]
@TaeZStkyoht try to specify lambda return type as `int`

**Comment by k06a** [comment]
Sad to hear that. This means our template to get return type is not working as expected.

**Comment by RoqueDeicide** [comment]
#61 Should fix this for good.

**Comment by TaeZStkyoht** [comment]
@RoqueDeicide nope. It will not be copiled gcc trunk and clang trunk. @k06a use my suggestion. This is the only compatible solution for now. If you decide not to support before C++17 in the future, just remove this definition and use invoke_result instead.
Here you can try on GodBolt: https://godbolt.org/z/GhfezTrnb

**Comment by TaeZStkyoht** [comment]
And lol @RoqueDeicide You just copied my code and created own pull request?
You commited 29 mins ago:
![image](https://user-images.githubusercontent.com/3801692/147828658-129510df-297c-4ec3-807a-6f0319626a80.png)

I commited 5 hours ago:
![image](https://user-images.githubusercontent.com/3801692/147828671-1069e353-1a79-483a-a82c-a62e0aa01552.png)

**Comment by TaeZStkyoht** [comment]
And after 5 hours try, I found compatible solution:
![image](https://user-images.githubusercontent.com/3801692/147828757-9451c058-fbb1-4456-acf1-201f0c4c992d.png)

**Comment by RoqueDeicide** [comment]
@TaeZStkyoht, My code is based on "possible implementation" section of `result_of` article on [cppreference.com](https://en.cppreference.com/w/cpp/types/result_of) Please, refrain from baseless accusations.

I'm not sure about compatibility with compilers that hadn't removed `result_of` as that just makes them not compatible with c++20 standard.

**Comment by k06a** [comment]
@TaeZStkyoht @RoqueDeicide thanks for the contributions, I will merge both and resolve conflicts 😁👌👍

**Comment by k06a** [comment]
Merged both, introduced subnamespace `priv` to avoid collisions incase of using both `std` and `boolinq` namespaces!
