### ISSUE TITLE
limits.h --> climits ?

### ISSUE THREAD

**Issue by peter-jansson** [k06a/boolinq#72]
Since this is a C++ header, shouldn’t \<climits\> be included instead of \<limits.h\> at the [third line](https://github.com/k06a/boolinq/blob/0df37ed90570a148c9d2395f5066313fd59247c9/include/boolinq/boolinq.h#L3)?

**Comment by k06a** [comment]
Let’s try to fix this!

**Comment by peter-jansson** [comment]
Fixed.
