### ISSUE TITLE
this is not LINQ

### ISSUE THREAD

**Issue by DBJDBJ** [k06a/boolinq#75]
At best this might be called "LINQ like API",  probably.

**Comment by k06a** [comment]
Could you explain?

**Comment by k06a** [comment]
It’s called “LINQ to Objects” in .NET: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/linq-to-objects

**Comment by DBJDBJ** [comment]
Linq is part of the language called C#
