### ISSUE TITLE
Custom containers

### ISSUE THREAD

**Issue by timluther** [k06a/boolinq#81]
Is there a list of requirements to make custom containers compatible with this library? I've implemented (c)begin/(c)end and most of everything I need for stl compatibility but don't know what boolinq requires.

**Comment by k06a** [comment]
@timluther as far as I can see:

https://github.com/k06a/boolinq/blob/2f0e6485ed7c42cf14a6289c04df1fcace354aac/include/boolinq/boolinq.h#L800-L812

So you need:
1. Any begin and end iterators, you can call them outside of the `from()` function call
2. Specify `std::iterator_traits` for your container ([read more here](https://stackoverflow.com/a/24893315))

**Comment by timluther** [comment]
Thanks, I got it working by providing being() and end() parameters rather than passing in the whole container - I think that only works if the container takes at least one template parameter? The particular container I wanted to use wasn't templatised.

Also, I had to fix my postfix inc/dec operators which were passing the modified iterator back when that's not what they should have done.

**Comment by k06a** [comment]
Yep, providing it as 1 arg is a bit tricky, begin and end operators are much more common way.
